# XRD for an XR API to create a IAM user with a specific resource access  
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xiamresourceusers.reference.imarunrk.com
spec:
  group: reference.imarunrk.com
  names:
    kind: XIAMResourceUser
    plural: xiamresourceusers
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          # Resource name, type and policy arn as API input
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  resorceName:
                    description: The name that is used for IAM user creation. User the same name as resource name for resorce policy lookup to work.
                    type: string
                  resorceType:
                    description: A string used as a part of prefix in IAM creation. 
                    type: string
                  policyARN:
                    description: ARN of the resource policy. User as a attachement to the user.
                    type: string
                required:
                  - resorceName
                  - resorceType
            required:
              - parameters